on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Choose where you want to publish the build'

jobs:
  test:
    steps:
      - name: 22f3001840@ds.study.iitm.ac.in
        run: echo "Hello, world!"
